export const EXPERIENCE_LIST = 'EXPERIENCE_LIST';
export const EXPERIENCE_ADD = 'EXPERIENCE_ADD';
export const EXPERIENCE_UPDATE = 'EXPERIENCE_UPDATE';
export const EXPERIENCE_REMOVE = 'EXPERIENCE_REMOVE';

export default {
  EXPERIENCE_LIST,
  EXPERIENCE_ADD,
  EXPERIENCE_UPDATE,
  EXPERIENCE_REMOVE,
}
